title: Sywid Tech Diaries (🌱 learning, unlearning, relearning)
description: Welcome to my discovery space, where I share my journey through the ever-evolving world of AI, cybersecurity and software development. Join me as I piece together my notes, ideas and thoughts, one page at a time.
theme: minima
